title: Chatbot Examples
description: >
  Chatlogs from various chatbot examples.
author:
  name: Ron Snyder
  email: ron@snyderjr.com

nav_pages:
  - about.md
show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

ghbase: "schh-commons/chatbot-examples/main"

content_selector: div.post-content,div.home

url: chatbot-examples