title: Chatbot Examples

description: >
  Chatlogs from various chatbot examples.

author:
  name: Ron Snyder
  email: ron@snyderjr.com

nav_pages:
  - about.md
  - chatbots.md
  - contact.md

max-width: 800px

show_excerpts: true
show_rss_feed: true

show_excerpts: true
show_rss_feed: true
show_github_link: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

contentSelector: div.post-content,div.home
ghbase: "schh-commons/chatbot-examples/main"
